# Generated by Django 4.1.1 on 2022-09-12 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
