# Generated by Django 4.1.1 on 2022-09-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogist', '0002_rename_post_id_comment_post_rename_user_id_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
