# Generated by Django 4.1.1 on 2022-09-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogist', '0004_post_media_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blogist', max_length=100)),
                ('title_align', models.CharField(default='center', max_length=50)),
                ('about', models.TextField(default='none')),
                ('about_img', models.TextField(default='none')),
                ('about_bg_color', models.CharField(default='white', max_length=50)),
                ('about_txt_color', models.CharField(default='black', max_length=50)),
                ('blog_bg_img', models.TextField(default='none')),
                ('blog_bg_color', models.CharField(default='white', max_length=50)),
                ('blog_txt_color', models.CharField(default='black', max_length=50)),
            ],
        ),
    ]
